# Generated by Django 4.2.4 on 2023-09-28 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_role_remove_userprofile_role_userprofile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game'),
        ),
        migrations.AlterField(
            model_name='team',
            name='numberOfPlayers',
            field=models.IntegerField(choices=[(4, 'Option 1'), (5, 'Option 2'), (6, 'Option 3')]),
        ),
    ]
