# Generated by Django 4.2.4 on 2023-09-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_team_members_alter_team_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bgmi_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bgmi_ign',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
