# Generated by Django 4.2.4 on 2023-10-03 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_team_creator_alter_team_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='static/images/')),
                ('logo', models.ImageField(upload_to='static/images/')),
                ('slots', models.IntegerField(blank=True, verbose_name='SLOTS')),
                ('starts_on', models.DateTimeField()),
                ('ends_on', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(default='static/images/noProfile.png', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='main.game'),
        ),
        migrations.DeleteModel(
            name='TeamDetail',
        ),
    ]
