# Generated by Django 4.2.4 on 2023-10-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tournament_userprofile_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(default='static/images/Profile.png', upload_to='static/images/'),
        ),
    ]
