# Generated by Django 4.2.4 on 2023-10-05 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_alter_tournament_logo_alter_tournament_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='RegOfTournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regOn', models.DateTimeField(auto_now_add=True)),
                ('regBy', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='registeredBy', to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='main.team')),
                ('tournament', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='main.tournament')),
            ],
        ),
    ]
