# Generated by Django 4.2.4 on 2023-10-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_tournament_main_image_regoftournaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='main.game'),
        ),
    ]
