# Generated by Django 4.2.4 on 2023-10-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_team_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(max_length=40, unique=True, verbose_name='Team Name'),
        ),
    ]
