# Generated by Django 4.2.4 on 2023-10-07 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_alter_team_teamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tournamentGame', to='main.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='manager',
            field=models.ManyToManyField(null=True, related_name='tournamentManagers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamCreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teamMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
