# Generated by Django 4.2.4 on 2023-10-07 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_tournament_game_tournament_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organiser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='manager',
            field=models.ManyToManyField(related_name='tournamentManagers', to=settings.AUTH_USER_MODEL),
        ),
    ]
