# Generated by Django 4.2.4 on 2023-10-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userprofile_is_organiser_alter_tournament_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bgmi_id',
            new_name='BatttleGroundMobileIndia_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='bgmi_ign',
            new_name='BatttleGroundMobileIndia_ign',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='CallOfDuty_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='CallOfDuty_ign',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ClashofClans_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ClashofClans_ign',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Volrant_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Volrant_ign',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
