# Generated by Django 4.2.4 on 2023-10-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_tournament_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regoftournaments',
            name='team',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamName', to='main.team'),
        ),
        migrations.AlterField(
            model_name='regoftournaments',
            name='tournament',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='main.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tournamentGame', to='main.game'),
        ),
    ]
