# Generated by Django 4.2.4 on 2023-10-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_regoftournaments_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='price',
            new_name='priceOfSlot',
        ),
        migrations.AddField(
            model_name='tournament',
            name='pricePool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registrations_ends_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registrations_starts_from',
            field=models.DateTimeField(null=True),
        ),
    ]
