# Generated by Django 4.2.4 on 2023-10-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_price_tournament_priceofslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registrations_starts_from',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
