# Generated by Django 4.2.4 on 2023-10-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_tournament_registrations_starts_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registrations_starts_from',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
