# Generated by Django 4.2.4 on 2023-10-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_tournament_registrations_starts_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registrations_starts_from',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
