# Generated by Django 4.2.4 on 2023-10-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_tournament_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organiser',
            field=models.CharField(default='Tmg esports.', max_length=100),
        ),
    ]
