# Generated by Django 4.2.4 on 2023-10-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_tournament_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='ends_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registrations_ends_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registrations_starts_from',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='starts_on',
            field=models.DateField(),
        ),
    ]
