# Generated by Django 4.2.4 on 2023-11-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_tournament_ends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organiser_staff',
            field=models.BooleanField(default=False),
        ),
    ]
