# Generated by Django 4.2.4 on 2023-11-11 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_userprofile_is_organiser_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.CharField(default=1, max_length=100, unique=True, verbose_name='Player One')),
                ('player_two', models.CharField(default=2, max_length=100, unique=True, verbose_name='Player Two')),
                ('player_three', models.CharField(default=3, max_length=100, unique=True, verbose_name='Player Three')),
                ('player_four', models.CharField(default=4, max_length=100, unique=True, verbose_name='Player Four')),
                ('player_five', models.CharField(blank=True, default=5, max_length=100, unique=True, verbose_name='Player Five')),
                ('player_six', models.CharField(blank=True, default=6, max_length=100, unique=True, verbose_name='Player Six')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamMembers', to='main.teammembers'),
        ),
    ]
