# Generated by Django 4.2.4 on 2023-11-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_teammembers_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamMembers', to='main.teammember'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_five',
            field=models.CharField(blank=True, default='---', max_length=100, unique=True, verbose_name='Player Five'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_four',
            field=models.CharField(default='---', max_length=100, unique=True, verbose_name='Player Four'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_one',
            field=models.CharField(default='---', max_length=100, unique=True, verbose_name='Player One'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_six',
            field=models.CharField(blank=True, default='---', max_length=100, unique=True, verbose_name='Player Six'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_three',
            field=models.CharField(default='---', max_length=100, unique=True, verbose_name='Player Three'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_two',
            field=models.CharField(default='---', max_length=100, unique=True, verbose_name='Player Two'),
        ),
    ]
