# Generated by Django 4.2.4 on 2023-11-27 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0029_remove_teammember_player_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='ends_on',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='starts_on',
        ),
        migrations.AddField(
            model_name='teammember',
            name='player_five',
            field=models.CharField(blank=True, default='---', max_length=100, unique=True, verbose_name='Player Five'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='player_four',
            field=models.CharField(default='---', max_length=100, unique=True, verbose_name='Player Four'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='player_one',
            field=models.CharField(default='---', max_length=100, unique=True, verbose_name='Player One'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='player_six',
            field=models.CharField(blank=True, default='---', max_length=100, unique=True, verbose_name='Player Six'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='player_three',
            field=models.CharField(default='---', max_length=100, unique=True, verbose_name='Player Three'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='player_two',
            field=models.CharField(default='---', max_length=100, unique=True, verbose_name='Player Two'),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamCreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamMembers', to='main.teammember'),
        ),
    ]
