# Generated by Django 4.2.4 on 2023-11-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_teammember_players_remove_tournament_ends_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='organiser',
            new_name='organisation',
        ),
    ]
