# Generated by Django 5.0.2 on 2024-02-15 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_organiser_tournament_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teammember'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_five',
            field=models.CharField(blank=True, default='player name', max_length=100, unique=True, verbose_name='Player Five'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_four',
            field=models.CharField(default='player name', max_length=100, unique=True, verbose_name='Player Four'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_one',
            field=models.CharField(default='player name', max_length=100, unique=True, verbose_name='Player One'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_six',
            field=models.CharField(blank=True, default='player name', max_length=100, unique=True, verbose_name='Player Six'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_three',
            field=models.CharField(default='player name', max_length=100, unique=True, verbose_name='Player Three'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_two',
            field=models.CharField(default='player name', max_length=100, unique=True, verbose_name='Player Two'),
        ),
    ]
