# Generated by Django 4.0.3 on 2024-05-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_team_members_alter_teammember_player_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='BatttleGroundMobileIndia_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='BatttleGroundMobileIndia_ign',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='CallOfDuty_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='CallOfDuty_ign',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ClashofClans_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ClashofClans_ign',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Volrant_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Volrant_ign',
        ),
    ]
