# Generated by Django 4.0.3 on 2024-05-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_userprofile_batttlegroundmobileindia_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_ign', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='game_info',
            field=models.ManyToManyField(to='main.gameinfo'),
        ),
    ]
