# Generated by Django 4.0.3 on 2024-05-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_gameinfo_userprofile_game_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='game_igid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
