# Generated by Django 4.0.3 on 2024-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_gameinfo_game_igid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='game_info',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='BatttleGroundMobileIndia_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='BatttleGroundMobileIndia_ign',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='CallOfDuty_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='CallOfDuty_ign',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ClashofClans_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ClashofClans_ign',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Volrant_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Volrant_ign',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_five',
            field=models.CharField(blank=True, default=' ', max_length=100, unique=True, verbose_name='Player Five'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_four',
            field=models.CharField(default=' ', max_length=100, unique=True, verbose_name='Player Four'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_one',
            field=models.CharField(default=' ', max_length=100, unique=True, verbose_name='Player One'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_six',
            field=models.CharField(blank=True, default=' ', max_length=100, unique=True, verbose_name='Player Six'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_three',
            field=models.CharField(default=' ', max_length=100, unique=True, verbose_name='Player Three'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_two',
            field=models.CharField(default=' ', max_length=100, unique=True, verbose_name='Player Two'),
        ),
        migrations.DeleteModel(
            name='GameInfo',
        ),
    ]
