# Generated by Django 4.0.3 on 2024-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_userprofile_game_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='player_four',
            field=models.CharField(blank=True, default=' ', max_length=100, unique=True, verbose_name='Player Four'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_one',
            field=models.CharField(blank=True, default=' ', max_length=100, unique=True, verbose_name='Player One'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_three',
            field=models.CharField(blank=True, default=' ', max_length=100, unique=True, verbose_name='Player Three'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_two',
            field=models.CharField(blank=True, default=' ', max_length=100, unique=True, verbose_name='Player Two'),
        ),
    ]
