# Generated by Django 4.0.3 on 2024-05-26 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0037_alter_teammember_player_four_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_created_on', models.DateTimeField(auto_now_add=True)),
                ('user_real_name', models.CharField(max_length=50)),
                ('request_subject', models.CharField(max_length=200)),
                ('request_message', models.TextField()),
                ('request_created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
