# Generated by Django 4.0.3 on 2024-05-26 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0038_usersupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersupport',
            name='request_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestCreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
