# Generated by Django 4.0.3 on 2024-05-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_usersupport_request_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='player_five',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Player Five'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_four',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Player Four'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_one',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Player One'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_six',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Player Six'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_three',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Player Three'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_two',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Player Two'),
        ),
    ]
