# Generated by Django 4.0.3 on 2024-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_teammember_player_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='player_five',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Player Five'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_four',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Player Four'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_one',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Player One'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_six',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Player Six'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_three',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Player Three'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_two',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Player Two'),
        ),
    ]
