# Generated by Django 4.0.3 on 2024-06-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_teammembership_remove_team_members_team_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='role',
        ),
    ]
