# Generated by Django 4.0.3 on 2024-06-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_teammembership_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userprofile'),
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]
