# Generated by Django 4.0.3 on 2024-06-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_team_members_team_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='numberOfPlayers',
            field=models.IntegerField(choices=[(4, '4 players'), (5, '5 players')]),
        ),
        migrations.CreateModel(
            name='TeamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.CharField(max_length=80, verbose_name='Player 1')),
                ('player_two', models.CharField(max_length=80, verbose_name='Player 2')),
                ('player_three', models.CharField(max_length=80, verbose_name='Player 3')),
                ('player_four', models.CharField(max_length=80, verbose_name='Player 4')),
                ('player_five', models.CharField(max_length=80, verbose_name='Player 5')),
                ('details_of_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
