# Generated by Django 4.0.3 on 2024-06-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_team_numberofplayers_teamdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamDetails',
            new_name='TeamDetail',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
