# Generated by Django 4.0.3 on 2024-06-29 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_roadmapoftournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapRoundsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_one', models.JSONField(default=None)),
                ('round_two', models.JSONField(default=None)),
                ('round_three', models.JSONField(default=None)),
                ('round_four', models.JSONField(default=None)),
                ('round_five', models.JSONField(default=None)),
                ('round_six', models.JSONField(default=None)),
                ('round_seven', models.JSONField(default=None)),
                ('round_eight', models.JSONField(default=None)),
                ('round_nine', models.JSONField(default=None)),
                ('round_ten', models.JSONField(default=None)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tournament')),
            ],
        ),
    ]
