# Generated by Django 4.0.3 on 2024-07-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_roadmaproundsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regoftournaments',
            name='tournament',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.tournament'),
        ),
    ]
