# Generated by Django 4.0.3 on 2024-07-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_regoftournaments_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_eight',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_five',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_four',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_nine',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_one',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_seven',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_six',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_ten',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_three',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_two',
            field=models.JSONField(blank=True, default=None),
        ),
    ]
