# Generated by Django 4.0.3 on 2024-07-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_roadmaproundsdetail_round_eight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_eight',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_five',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_four',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_nine',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_one',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_seven',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_six',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_ten',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_three',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='round_two',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
