# Generated by Django 5.0.7 on 2024-08-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_roadmaproundsdetail_round_eight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.tournament'),
        ),
    ]
