# Generated by Django 5.0.7 on 2024-08-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_roadmaproundsdetail_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmaproundsdetail',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
