# Generated by Django 5.0.7 on 2024-08-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_roadmaproundsdetail_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(default='static/images/Profile.png', upload_to='media/images/'),
        ),
    ]
