# Generated by Django 5.0.7 on 2024-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_userprofile_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(default='static/images/Profile.png', upload_to='userProfile/images/'),
        ),
    ]
