# Generated by Django 5.0.7 on 2024-08-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_userprofile_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournament/images/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament/images/'),
        ),
    ]
