# Generated by Django 5.0.7 on 2024-08-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_tournament_logo_alter_tournament_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, default='static/images/MainBg.jpg', null=True, upload_to='tournament/images/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='main_image',
            field=models.ImageField(blank=True, default='static/images/MainBg.jpg', null=True, upload_to='tournament/images/'),
        ),
    ]
